### ISSUE TITLE
Một số liên kết không thực hiện được

### ISSUE THREAD

**Issue by nguyennampotter** [nukeviet/module-weblink#11]
Tình hình là thêm link tốt, nhưng có một số không được, mình bị 2 link: xaydung.gov.vn và soyte.kiengiang.gov.vn khi thêm thì nó báo lỗi: "Lỗi đường dẫn không hợp lệ hoặc giống với một liên kết trong cơ sở dữ liệu."
Xin hỏi cách khắc phục. Xin cám ơn!

**Comment by hoaquynhtim99** [comment]
Hiện tại đã bỏ phần kiểm tra URL. theo https://github.com/nukeviet/module-weblinks/commit/a8b023895717e01de23d383b529f5ddff1d7ab50
