### ISSUE TITLE
Không kích hoạt được blok lieenk kết ở ngoài site

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/module-weblink#12]
Đã cài bản mới nhất, khi mở tính năng keo thả block, làm xong báo thành công nhưng không hiện lên gì cả
![image](https://cloud.githubusercontent.com/assets/14310636/24835204/1d0ffb7a-1d25-11e7-99f3-fd4f50a52266.png)

**Comment by hoaquynhtim99** [comment]
Bạn kiểm tra lại cái này nhé, hiện không có lỗi này, block đó chỉ hiển thị ở module và hiển thị khi có "Chủ đề liên kết" nếu bạn chưa thêm chủ đề liên kết thì nó không hiện cái gì
