### ISSUE TITLE
Lỗi chuyển liên kết không đúng 

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-weblink#6]
Lỗi chuyển liên kết không đúng là khi thêm nhiều liên kết vào thì khi vào Link tới website:  URL ví dụ có ip là 5 thì nó lại chuyển về link web có ip là 1. Bất kỳ link web nào thì khi link vào thì diều bị chuyển về liên kết mà đã nhập vào đầu tiên và có ip là nhỏ nhất.
Phiên bản: Nukeviet 4.0.23 và module-weblink 4.0.22

**Comment by webvangvn** [comment]
fix https://github.com/nukeviet/module-weblink/pull/7

**Comment by NukeVietCMS** [comment]
Sửa như vầy mới Ok được.
<?php
/**
- @Project NUKEVIET 4.x
- @Author VINADES.,JSC (contact@vinades.vn)
- @Copyright (C) 2014 VINADES.,JSC. All rights reserved
- @License GNU/GPL version 2 or any later version
- @Createdate 3-6-2010 0:14
  */
  if( ! defined( 'NV_IS_MOD_WEBLINKS' ) ) die( 'Stop!!!' );
  global $timeout;
  $id = 0;
  $temp = explode( '-', $array_op[0] );
  $id = intval( end( $temp ) );
  +$sql = 'SELECT url FROM ' . NV_PREFIXLANG . '_' . $module_data . '_rows WHERE id=' . intval( $id ) . ' LIMIT 0,1';
  $result = $db->query( $sql );
  $row = $result->fetch();
  if( $row['url'] != '' )
  {
  if( ! preg_match( '/http:\/\//i', $row['url'] ) )
  {
      $url = 'http://' . $url;
  }
  if( isset( $_COOKIE['timeout'] ) and $_COOKIE['timeout'] == $id )
  {
      $contents .= sprintf( $lang_module['notimeout'], $timeout );
  }
  else
  {
      setcookie( 'timeout', $id, time() + $timeout \* 60 );
      $db->query( 'UPDATE ' . NV_PREFIXLANG . '_' . $module_data . '_rows SET hits_total=hits_total+1 WHERE id=' . intval( $id ) );
  }
  Header( 'Location: ' . $row['url'] );
  exit();
  }
  include NV_ROOTDIR . '/includes/header.php';
  echo nv_site_theme( $contents );
  include NV_ROOTDIR . '/includes/footer.php';
