### ISSUE TITLE
Cấu hình Liên kết không lưu được

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-weblink#8]
Khi thay đổi các thông số trong phần cấu hình liên kết [config] rồi bấn [chấp nhận] thì thấy giống như đã được lưu rồi nhưng khi chọn lại link [Cấu hình Liên kết] thì thấy không hề lưu những gì đã thay đổi. Xem ngoài site thì vẫn thế không hề thay đổi gì cả.
Site sử dụng: 
Nukeviet 4.0.23
module-weblink 4.0.22.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/nukeviet/module-weblink/commit/048a7735f653e3f5c344151390b380937ce03474
